spring.data.mongodb.uri=mongodb+srv://ramanjanb708_db_user:SzmFaKeg8peLia33@cluster0.u98cadq.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldatabase
spring.data.mongodb.auto-index-creation=true



